### ISSUE TITLE
Possible Steam synchronisation of game progress?

### ISSUE THREAD

**Issue by dClauzel** [The-Dumb-Dino/Dinos-Hyperspace-Wrapper-for-Mac#2]
The wrapper works fine on my Mac (Retina 5K 27" late 2015 with OpenCore-Patcher for keeping up with the current version of MacOS.) Sounds and images are fine, the game is fluid. Pretty nice work!

I am wondering how I could sync the game progresses that is usually do on my Chromebook (steam version)?

I suppose I could simply manually sync the files located in `~/Documents/My Games/FasterThanLight/hs_mv_*`, but is there a proper way to do it without messing with both installations? Maybe through Steam sync?

The FTL multiverse versions on the Chromebook and the Mac are both up to date.

**Comment by The-Dumb-Dino** [comment]
First of:
hs_, hs_mv or any other save with some special prefix is notbeing synced on steam only the vanilla saves whis makes this pretty pointless already. 

Second:
The wrapper application is not actually a programm, but rather a huge script packed as a Mac app. The script wouldn't allow such magic. I'd need to rewrite the wrapper in an actuall programming Langauge so I'd have more possibilities for matters like that.

So no, this won't be added, sorry.
A rewrite is also unlikely because at the current point of time a native hyperspace mac Release id more likely than it ever was before.

**Comment by dClauzel** [comment]
OK, thanks! So I will transfer the files manually (by that I mean with script based automation 😃)
